export const mockGroups = [
  {
    id: '1',
    name: 'Vegas Sharks',
    description: 'High-stakes betting group for NFL games.',
    memberCount: 12,
    maxMembers: 20,
    pickDueDay: 'Thursday',
    betAmount: 50,
    wins: 30,
    losses: 10,
    isMember: true,
    members: [
      { name: 'John Doe', wins: 10, losses: 5, role: 'admin' },
      { name: 'Jane Smith', wins: 8, losses: 7, role: 'member' },
      { name: 'Bob Wilson', wins: 5, losses: 10, role: 'member' },
      { name: 'Alice Johnson', wins: 7, losses: 8, role: 'member' },
    ],
  },
  {
    id: '2',
    name: 'NBA Ballers',
    description: 'Focused on NBA player props and game lines.',
    memberCount: 8,
    maxMembers: 15,
    pickDueDay: 'Friday',
    betAmount: 25,
    wins: 15,
    losses: 5,
    isMember: true,
    members: [
      { name: 'Michael Jordan', wins: 20, losses: 3, role: 'admin' },
      { name: 'LeBron James', wins: 18, losses: 5, role: 'member' },
      { name: 'Kobe Bryant', wins: 15, losses: 8, role: 'member' },
    ],
  },
  {
    id: '3',
    name: 'Soccer Stars',
    description: 'Betting on international soccer matches.',
    memberCount: 18,
    maxMembers: 20,
    pickDueDay: 'Saturday',
    betAmount: 10,
    wins: 20,
    losses: 15,
    isMember: false,
    members: [
      { name: 'Lionel Messi', wins: 25, losses: 5, role: 'admin' },
      { name: 'Cristiano Ronaldo', wins: 22, losses: 8, role: 'member' },
    ],
  },
  {
    id: '4',
    name: 'MLB Legends',
    description: 'Baseball betting group for MLB games.',
    memberCount: 5,
    maxMembers: 10,
    pickDueDay: 'Wednesday',
    betAmount: 100,
    wins: 10,
    losses: 8,
    isMember: false,
    members: [
      { name: 'Babe Ruth', wins: 30, losses: 10, role: 'admin' },
      { name: 'Hank Aaron', wins: 25, losses: 15, role: 'member' },
    ],
  },
];